require 'rubygems'
require 'active_record'
require 'active_support'
require 'yaml'
require 'rake'
require 'logger'

desc "Migrate the database through scripts in this folder. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('.', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :rollback => :environment do
  ActiveRecord::Migrator.rollback('.')
end

task :environment do
  ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml'))[ENV["RAILS_ENV"] ? ENV["RAILS_ENV"] : "development"])
  ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
end

task :default => :migrate
