require 'rubygems'
require 'fileutils'
require 'jake'

desc "Compile jkey-extractor"
task :build => :clean do
  Javac.in('.').execute do |javac|
    javac.src = 'src/**/*.java'
    javac.cp << 'lib/**/*.jar'
    javac.output = 'bin'
  end
end

desc "Clean jkey-extractor build"
task :clean do
  FileUtils.rm_rf Dir.glob('bin/*')
end

desc "Create jkey-extractor.jar"
task :jar do
  Jar.in('.').execute do |jar|
    jar.name = 'jkeyextractor.jar'
    jar.bin << 'bin'
    jar.bin << 'etc'
  end
end

task :default => [":build", ":jar"]
