# {{{ jkeyextractor
namespace :jkeyextractor do
  desc "Compile jkey-extractor"
  task :build => :clean do
    Javac.in(JKEY_DIR).execute do |javac|
      javac.src = 'src/**/*.java'
      javac.cp << 'lib/**/*.jar'
      javac.output = 'bin'
    end
  end

  desc "Clean jkey-extractor build"
  task :clean do
    Dir.chdir(JKEY_DIR) do
      FileUtils.rm_rf Dir.glob('bin/*')
    end
  end

  desc "Create jkey-extractor.jar and move it (and its dependencies) to PLUGINS_DIR's external_lib"
  task :jar do
    Jar.in(JKEY_DIR).execute do |jar|
      jar.name = 'jkeyextractor.jar'
      jar.bin << 'bin'
      jar.bin << 'etc'
    end

    FileUtils.cp("#{JKEY_DIR}/jkeyextractor.jar", "#{PLUGINS_DIR}/external_libs")
    FileUtils.cp_r(Dir.glob("#{JKEY_DIR}/lib/*"), "#{PROXY_DIR}/libs")
  end
end
# }}}